okta:
  oauth2:
    issuer: https://dev-cvij12nrjpduiobw.us.auth0.com/
    client-id: KaDmf8L3mI4Euq4fWC43Ugrnuen6Na66
    client-secret: 5l-Jf0tSDiKLK9ibO3vq_ijOPSQsWd36nAqBjEVIRk4lXf6KT9Z3UcwjB7AtiNG5

## SECRET VALUES FOR SPRINGBOOT
#  export ISSUER_ACEBOOK="https://dev-cvij12nrjpduiobw.us.auth0.com/"
#  export CLIENT_ID_ACEBOOK="KaDmf8L3mI4Euq4fWC43Ugrnuen6Na66"
#  export CLIENT_SECRET_ACEBOOK="5l-Jf0tSDiKLK9ibO3vq_ijOPSQsWd36nAqBjEVIRk4lXf6KT9Z3UcwjB7AtiNG5"